### ISSUE TITLE
Funktion __cocodaHttpRequest liefert keine Mappings

### ISSUE THREAD

**Issue by DavidBRohrer** [gbv/cocoda-winibw#15]
Beim Test in der WinIBW bekomme ich immer die Meldung "Keine Normdaten-Mappings gefunden".
Mir scheint es so, dass die Funktion __cocodaHttpRequest nicht korrekt funktioniert. 
Die URL, die in Zeile 119 übergeben wird, ist jedenfalls korrekt zusammengesetzt.

**Comment by stefandesu** [comment]
Das Problem ist, dass WinIBW3 keine Abfragen über HTTPS unterstützt. Wir haben deshalb entschieden, nur WinIBW4 zu unterstützen: #19
