### ISSUE TITLE
Use only one browser window

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda-winibw#2]
When using the script cocodaURL it should open in the same Tab you are currently in, furthermore opening new Tabs everytime slows down your browser, so it should be avoided.

**Comment by cKlee** [comment]
I think this can only be done by a browser preference.

**Comment by stefandesu** [comment]
The problem is that, to achieve this, the script would have to communicate directly with the tab inside the browser. I'm not sure if this is even possible at all.

**Comment by nichtich** [comment]
We could create a hack by

* [ ] configuring a "remote control token" in WinIBW (requires #7)
* [ ] building a remote control web service that WinIBW send commands to (for instance the full query URL of Cocoda)
* [ ] extend Cocoda to listen to the remote control webservice

**Comment by stefandesu** [comment]
This is not implemented, right? I'll change it to "not planned".
