### ISSUE TITLE
Mappings in WinIBW anzeigen

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda-winibw#8]
Eine Funktion, damit man in WinIBW Mappings anzeigen kann sollte implementiert werden.

**Comment by cKlee** [comment]
Achtet darauf, dass die WinIBW in den Standard-Scripts kein HTTPS unterstützt.

**Comment by stefandesu** [comment]
Unsere API ist auch mit HTTP erreichbar. Hier ein kurzes Beispiel für eine HTTP-Abfrage via WinIBW: https://github.com/gbv/cocoda-winibw/wiki/HTTP-Abfragen

**Comment by stefandesu** [comment]
Es gibt jetzt eine erste Implementation von einer `cocodaMappings`-Funktion, die Mappings zu allen gefundenen Konzepten im Datensatz von der API abfragt und in Textform in einer messageBox anzeigt. Bisher kann man jedoch nichts weiter mit den Mappings machen. 

Außerdem ist die Funktion noch nicht sonderlich gut getestet. In meinen Tests hat es funktioniert, aber es wäre gut, das ganze mit mehr Beispielen zu testen (siehe #13).
